spring.application.name=api

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:api
spring.jpa.hibernate.ddl-auto=update

spring.datasource.username=sa
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.h2.console.path=/h2-console

// Configuration JWT
# JWT secret
app.jwt.secret=foodshare-secret-key-must-be-256-bits-long!!
app.jwt.expiration-ms=86400000


